version: "3"
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Abc@4321
    volumes:
        - './drive:/var/opt/mssql'
    networks:
      - todo_app

networks:
  todo_app:
    name: todo_app_network

